version: '3.4'

services:
  hello-world-svc:
    image: hello-world-svc:latest
    build:
      context: ./hello-world-svc
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  hello-svc:
    image: hello-svc:latest
    build:
      context: ./hello-svc
      dockerfile: ./Dockerfile
    expose:
      - 8080
  world-svc:
    image: world-svc:latest
    build:
      context: ./world-svc
      dockerfile: ./Dockerfile
    expose:
      - 8080
